Modify the tests to test RFC7951#section-6.8 compliance
alliedtelesis/apteryx-rest pull request #41
Opened 2024-07-16 03:36 UTC by gcampbell512

RFC7951 https://datatracker.ietf.org/doc/html/rfc7951#section-6.8

A change was made to apteryx-xml schema.c to support RFC7951#section-6.8 compliance. An additional change to test.xml changed the responses in certain tests. This change modifies the various tests to reflect the expected modified output.

2024-07-16 03:39 UTC, tony-vanderpeet approved these changes

2024-07-16 06:35 UTC, carlgsmith requested changes
Restapi tests should not expect prefixed node names. Fix schema.c

2024-07-16 23:10 UTC, tony-vanderpeet reviewed
OK, I see now how it works. I think I'll wait for Carl to comment...

2024-07-19 05:05 UTC, carlgsmith approved these changes

2024-07-19 05:06 UTC, carlgsmith approved these changes

2024-07-19 05:06 UTC, merged