Fix the response to the resconf depth parameter
alliedtelesis/apteryx-rest pull request #51
Opened 2024-09-23 02:30 UTC by gcampbell512

RFC 8040 section B.3.2 gives examples of how to respond to the depth parameter on a restconf query. The current output is not consistent with the example output.

2024-09-23 02:31 UTC, gcampbell512 commented
This change requires a change to apteryx-xml (currently in review)

2024-09-24 19:04 UTC, carlgsmith requested changes

2024-09-24 19:04 UTC, carlgsmith commented on tests/test_query.py
> +        "description": {},
these are leaves not containers ... hence should not return an empty json object

2024-09-24 21:02 UTC, tony-vanderpeet commented on rest.c
> +                if (json_is_array (child) && json_is_array (t_child))
save an indent, use else if

2024-09-24 21:07 UTC, tony-vanderpeet reviewed
You're right, this does look like what I described yesterday with respect to the add defaults code. I am intrigued by the array part of the merge routine, there doesn't need to be any checking that the array elements in template can all be applied to all of the array elements in child?

2024-09-25 22:20 UTC, tony-vanderpeet approved these changes

2024-09-26 19:23 UTC, carlgsmith approved these changes

2024-09-26 19:23 UTC, merged